### PR TITLE
Add release_url param to the download_specs function

### PR DESCRIPTION
**Pull request by jayrbolton**
This is a minimalistic way for us to be able to update the specs to prerelease, or even roll back the specs to previous versions, by specifying the url of the release in the url params to /api/update_specs

I'm thinking about how to test this.. in the mean time would appreciate any feedback

### CODE REVIEW

**Comment by jayrbolton** [comment]
Potentially closes #13, albeit a little different approach #

**Comment by jayrbolton** [comment]
I'll add docs on this (we need that readme checkbox lol)

**Comment by JamesJeffryes** [comment]
Looks like I can't edit the module setting to add a PR template

**Comment by jayrbolton** [comment]
Okay, updated docs.

**Pull request merged**
